In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression

In [2]:
df= pd.read_csv('Algerian_forest_fires_cleaned_dataset.csv')
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire,0
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,0
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,26,9,2012,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,fire,1
239,27,9,2012,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,not fire,1
240,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire,1
241,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire,1
242,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    object
 14  Region       243 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 28.6+ KB

In [4]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='object')

In [5]:
df.drop(['day', 'month', 'year'], axis= 1, inplace=True)

In [6]:
df.reset_index()

,index,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,0,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,1,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire,0
2,2,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,3,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,0
4,4,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,238,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,fire,1
239,239,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,not fire,1
240,240,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire,1
241,241,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire,1
242,242,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire,1

In [7]:
df['Classes']= np.where(df['Classes'].str.contains('not fire'), 0,1)
df

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0,0
1,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0,0
2,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0,0
3,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0,0
4,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
238,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,1,1
239,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,0,1
240,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0,1
241,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0,1
242,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0,1

In [8]:
df['Classes'].value_counts()

Classes
1    137
0    106
Name: count, dtype: int64

In [9]:
x= df.drop(['Classes'], axis=1)
y= df['Classes']

In [10]:
x

     Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  FWI  Region
0             29  57  18   0.0  65.7   3.4   7.6  1.3   3.4  0.5       0
1             29  61  13   1.3  64.4   4.1   7.6  1.0   3.9  0.4       0
2             26  82  22  13.1  47.1   2.5   7.1  0.3   2.7  0.1       0
3             25  89  13   2.5  28.6   1.3   6.9  0.0   1.7  0.0       0
4             27  77  16   0.0  64.8   3.0  14.2  1.2   3.9  0.5       0
..           ...  ..  ..   ...   ...   ...   ...  ...   ...  ...     ...
238           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9  6.5       1
239           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2  0.0       1
240           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4  0.2       1
241           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1  0.7       1
242           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8  0.5       1

[243 rows x 11 columns]

In [11]:
x_train, x_test, y_train,y_test= train_test_split(x, y, test_size=0.2, random_state=25)
print(x_train.shape)
print(x_test.shape)

(194, 11)
(49, 11)

In [12]:
scaler= StandardScaler()
x_train_scaled= scaler.fit_transform(x_train)
x_test_scaled= scaler.transform(x_test)

In [13]:
x_train_scaled

array([[-2.8176204 ,  0.95754747,  3.60623292, ..., -1.05075974,
        -0.91893417, -0.96953597],
       [-0.87925743,  0.88889846,  0.10818699, ..., -0.80509282,
        -0.69977384, -0.96953597],
       [-1.15616643,  1.23214349,  1.85720995, ..., -0.58048307,
        -0.89153913, -0.96953597],
       ...,
       [ 0.50528755,  0.61430244, -0.5914222 , ..., -0.9173977 ,
        -0.87784161,  1.03142125],
       [ 0.78219655, -0.48408165, -1.29103138, ..., -0.7770166 ,
        -0.82305153, -0.96953597],
       [-0.32543944, -1.37651872,  1.85720995, ...,  0.10036525,
         1.35485423,  1.03142125]], shape=(194, 11))

In [14]:
import pickle
pickle.dump(scaler, open("scaler.pkl", 'wb'))

In [16]:
logistic_reg= LogisticRegression()
logistic_reg.fit(x_train_scaled, y_train)
y_pred= logistic_reg.predict(x_test_scaled)

In [17]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

accuracy= accuracy_score(y_test, y_pred)
cm= confusion_matrix(y_pred, y_test)
report= classification_report(y_pred, y_test)

print(f"accuracy: {accuracy}")
print(cm)
print(f"Classification_report: {report}")

accuracy: 1.0
[[18  0]
 [ 0 31]]
Classification_report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        31

    accuracy                           1.00        49
   macro avg       1.00      1.00      1.00        49
weighted avg       1.00      1.00      1.00        49